 "use client"
import { Inter } from "next/font/google";
import "../../app/globals.css";
import Navbar from "@/components/(AdminPanel)/Navbar/Navbar";
import SideBar2 from "@/components/(AdminPanel)/Sidebar/Sidebar2";
import { ThemeProvider } from "@/components/ThemContext/theme";
import { useAuthRedirect } from "@/utilities/Authentication";



const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Flex E Market",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)


{

  const isAuthenticated = useAuthRedirect();

  if (!isAuthenticated) return null;


  return (
    <html lang="en">
      {/* <body className={inter.className} > */}
      <body>
  
  <ThemeProvider>


<div className="flex"> 
<SideBar2 />

<div className="w-full ">
<Navbar />


<div className="p-4 pt-8 w-full flex flex-wrap flex-col justify-between overflow-x-auto">

      {children}
</div>


</div>



</div>

</ThemeProvider>


        
        
{/* </NotificationProvider> */}
        </body>
    </html>
  );
}
