import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import "../globals.css";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        
      <div className="p-4 pt-8 w-full flex flex-wrap flex-col justify-between overflow-x-auto">

      {children}

    </div>
<p className="text-gray-400 absolute w-full bottom-0 flex justify-center">© 2024 ALL RIGHTS RESERVED</p>

      </body>
    </html>
  )
}
